<?php
namespace Xymon\Channel;

use Xymon\Utility\BasicEnum;

/**
 * These are the types of messages that can come across
 * the various Xymond channels.
 *
 * @see {xymonsourcode}/xymond/xymond_sample.c
 * @see {xymonsourcode}/xymond/new-daemon.txt
 */
abstract class ProtocolType extends BasicEnum
{
    /**
     * Ack messages
     */
    const Ack = 'ack';

    /**
     * Client change message.
     */
    const Clichg = 'clichg';

    /**
     * Client messages.
     */
    const Client = 'client';

    /**
     * Data
     */
    const Data = 'data';

    /**
     * Drop host messages.
     */
    const Drophost = 'drophost';

    /**
     * Drop test messages.
     */
    const Droptest = 'droptest';

    /**
     * Dropstate
     */
    const Dropstate = 'dropstate';

    /**
     * Enable/disable messages.
     */
    const Enadis = 'enadis';

    /**
     * When a timeout happens getting a message you may get an 'idle'
     */
    const Idle = 'idle';

    /**
     * This message is sent when xymon logs are rotated.
     */
    const Logrotate = 'logrotate';

    /**
     * Notes
     */
    const Notes = 'notes';

    /**
     * Notify
     */
    const Notify = 'notify';

    /**
     * Pages/alert messages.
     */
    const Page = 'page';

    /**
     * Typically 'reload' means the hosts.cfg file has changed.
     * But it most likely means the hosts.cfg file has been
     * re-read by the daemon.
     */
    const Reload = 'reload';

    /**
     * Rename host messages.
     */
    const Renamehost = 'renamehost';

    /**
     * Rename test messages.
     */
    const Renametest = 'renametest';

    /**
     * Sent when master daemon terminates.
     */
    const Shutdown = 'shutdown';

    /**
     * Status change message.
     */
    const Stachg = 'stachg';

    /**
     * All statuses received and/or generated by Xymond.
     */
    const Status = 'status';
}
